version: 2.1
executors:
  unity:
    docker:
      - image: gableroux/unity3d:2018.2.21f1
jobs:
  build_StandaloneLinux64:
  steps:
  - run:
      environment:
        BUILD_TARGET: StandaloneLinux64
  - store_artifacts:
      path: "./Builds/"
workflows:
  version: 2
  build:
    jobs:
      - build_StandaloneLinux64
