version: 2.1
executors:
  unity:
    docker:
      # https://hub.docker.com/r/gableroux/unity3d/tags
      - image: gableroux/unity3d:2018.2.21f1-windows
references:
  docker_image: &docker_image
jobs:
  build_StandaloneLinux64:
    <<: *docker_image
    steps:
    - run:
        command: apt-get update && apt-get install -y git && git --version
    - checkout
    - run:
        environment:
          BUILD_TARGET: StandaloneLinux64
    - store_artifacts:
        path: "./Builds/"
workflows:
  version: 2
  build:
    jobs:
      - build_StandaloneLinux64
